/*------------------------------------------------------------------------
    File        : TermsEnum
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : mikef
    Created     : Tue Jul 04 13:50:59 CEST 2017
    Notes       : 
  ----------------------------------------------------------------------*/

ENUM TrainingSamples.BusinessLogik.TermsEnum :  

    DEFINE ENUM Net10 = 10 
                Net15 = 15 
                Net30 = 30 
                Net60 = 60 .     

END ENUM.
